name = "scf-discord-bot"

compatibility_date = "2022-04-05"

usage_model="unbound"

kv_namespaces = [
    { binding = "SESSION_STORAGE", id = "8b7d15e78c0c42deb9fceb8b05190a7c", preview_id = "4bcd720d70ef4bd9ab1e0bd3b952305b" },
    { binding = "TOMLKEYS", id = "b2b65162e00a4ac785aa0b77e8660df2", preview_id = "c5e77c42db1b402d92ae819117bcced3" },
    { binding = "ROLEDATA", id = "5ca8bd87c38347119999a0f36f3097a2", preview_id = "6ba22652d4ab4170a406a2e26928ed9f" }
]
[site]
  bucket = "./public"
[build]
  command = "npm run build"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "SCFDBDATA"
database_id = "6120043f-d1e6-409f-850a-6892e3257253"