name = "stellar-discord-bot"
compatibility_date = "2023-02-23"
kv_namespaces = [
    { binding = "SESSION_STORAGE", id = "3e72ac9816ab45909c493267dac88d1b", preview_id = "51bb79ab719b4271aedc5f9556beec8d" },
    { binding = "TOMLKEYS", id = "20aae67ac807482098ad13f1ca7e4337", preview_id = "fb2d0cdb0c9c4f1986221338ece1b44d" },
    { binding = "ROLEDATA", id = "0f5933381b0a43a8b658b912f0c6a984", preview_id = "7de201d67bbc4da8a5b96fbf10f05b79" }
]
[site]
  bucket = "./public"
[build]
  command = "npm run build"
[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "SDBDATA"
database_id = "8a4b3992-9618-4a2e-b948-c39b4290e922"
