name = "stellar-discord-bot"
compatibility_date = "2023-02-23"
kv_namespaces = [
    { binding = "SESSION_STORAGE", id = "3e72ac9816ab45909c493267dac88d1b" },
    { binding = "TOMLKEYS", id = "20aae67ac807482098ad13f1ca7e4337" }
]
[site]
  bucket = "./public"
[build]
  command = "npm run build"
[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "SDBDATA"
database_id = "8a4b3992-9618-4a2e-b948-c39b4290e922"
